"""initial schema

Revision ID: 573844d5005c
Revises: 
Create Date: 2026-06-29 17:39:36.135887
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '573844d5005c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('group', sa.Enum('city', 'regional', 'departmental', 'satgo', name='categorygroup'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('form_schema', sa.JSON(), nullable=False),
    sa.Column('edition_year', sa.Integer(), nullable=False),
    sa.Column('voting_enabled', sa.Boolean(), nullable=False),
    sa.Column('nominations_open', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'judge', name='userrole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('nominator_name', sa.String(length=200), nullable=True),
    sa.Column('nominator_contact', sa.String(length=200), nullable=True),
    sa.Column('residency', sa.String(length=120), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'shortlisted', 'rejected', name='nominationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominations_category_id'), 'nominations', ['category_id'], unique=False)
    op.create_index(op.f('ix_nominations_status'), 'nominations', ['status'], unique=False)
    op.create_table('nomination_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomination_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomination_files_nomination_id'), 'nomination_files', ['nomination_id'], unique=False)
    op.create_table('nominees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source_nomination_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('edition_year', sa.Integer(), nullable=False),
    sa.Column('is_shortlisted', sa.Boolean(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['source_nomination_id'], ['nominations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominees_category_id'), 'nominees', ['category_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomination_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomination_id', 'judge_id', name='uq_score_once')
    )
    op.create_index(op.f('ix_scores_judge_id'), 'scores', ['judge_id'], unique=False)
    op.create_index(op.f('ix_scores_nomination_id'), 'scores', ['nomination_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nominee_id', sa.Integer(), nullable=False),
    sa.Column('voter_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nominee_id'], ['nominees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nominee_id', 'voter_fingerprint', name='uq_vote_once')
    )
    op.create_index(op.f('ix_votes_nominee_id'), 'votes', ['nominee_id'], unique=False)
    op.create_index(op.f('ix_votes_voter_fingerprint'), 'votes', ['voter_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_voter_fingerprint'), table_name='votes')
    op.drop_index(op.f('ix_votes_nominee_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_scores_nomination_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_judge_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_nominees_category_id'), table_name='nominees')
    op.drop_table('nominees')
    op.drop_index(op.f('ix_nomination_files_nomination_id'), table_name='nomination_files')
    op.drop_table('nomination_files')
    op.drop_index(op.f('ix_nominations_status'), table_name='nominations')
    op.drop_index(op.f('ix_nominations_category_id'), table_name='nominations')
    op.drop_table('nominations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
